project:
  type: book
  output-dir: docs

execute:
  echo: true
  warning: false
  message: false

toc: true
toc-depth: 3
# bibliography: references.bib

book:
  title: "Documentation for ARC"
  author:
  - John J. Curtin, PhD
  - Kendra Wyant, MS
  - Susan Wanta, MS
  site-url: https://github.io/jjcurtin/docs_arc
  repo-url: https://github.com/jjcurtin/docs_arc
  repo-branch: main
  repo-actions: [edit]
  sharing: [facebook, linkedin]
  page-navigation: true
  chapters:
    - index.qmd
    - lab_practices.qmd
    - grad_expectations.qmd
    - studies.qmd
    - chtc.qmd
    - git.qmd
    - linux_install.qmd
    - linux_use.qmd
    - vim.qmd
    - flowchart_demo.qmd
    - studies.qmd
    - part: "Other Software"
      chapters:
        - globalprotect_mapping.qmd
        - zotero.qmd
        - qr_code.qmd
    - psychophysiology.qmd
