project:
  type: book

execute:
  echo: true
  warning: false
  message: false

toc: true
toc-depth: 3

book:
  title: "Documentation for ARC"
  author:
  - John J. Curtin, PhD
  - Kendra Wyant, MS
  - Susan Wanta, MS
  site-url: https://github.io/jjcurtin/docs_arc
  repo-url: https://github.com/jjcurtin/docs_arc
  page-navigation: true
  chapters:
    - index.qmd
    - lab_practices.qmd
    - grad_expectations.qmd
    - studies.qmd
    - resources.qmd
    - chtc.qmd
    - flowchart_demo.qmd
    - research_drives.qmd
    - virtual_machines.qmd
    - part: Linux and CLI
      chapters:
        - git.qmd
        - linux_install.qmd
        - linux_use.qmd
        - vim.qmd
        - bash_scripting.qmd
        - shell_expansions.qmd
    - part: "Other Software"
      chapters:
        - globalprotect_mapping.qmd
        - zotero.qmd
        - qr_code.qmd
    - part: "Psychophysiology"
      chapters:
        - psychophysiology.qmd
        - psychophysiology_software.qmd
