# Engagement Resources

This page details resources for community engagement, both on- and off-campus.

## On-campus resources

### [Wisconsin Network for Research Support (WINRS)](https://winrs.nursing.wisc.edu/)

Located in the School of Nursing on the UW-Madison campus, WINRS offers a bridge between research groups and community members through their maintenance of several community advisory boards (CABs).

WINRS staff work with research teams to identify and prepare meeting agendas. Staff also coordinate all meeting logistics and facilitate CARDS sessions. Following meetings, WINRS staff prepare and deliver feedback reports.

Useful contact: Kat Phelps, kephelps\@wisc.edu

#### [Community Advisors on Research Design & Strategies (CARDS)](https://winrs.nursing.wisc.edu/cards/)

There are two CABs through CARDS. Each group has approximately 12 members (affiliated with the Goodman Community Center and Lussier Community and Education Center).

Members of these groups were recruited from "community center programs such as senior meals, women's groups, food pantries, and parenting programs."

#### [Boards of Older Adult Advisors (BOAAs)](https://winrs.nursing.wisc.edu/board-of-older-adult-advisors/)

In coordination with the Center for Aging Research and Education (CARE) within the School of Nursing, WINRS maintains two advisory boards focused on providing feedback relating towards aging and the well-being of older adults.

One board is based in Madison, Wisconsin and one board consists of members from rural communities across Wisconsin. Madison BOAA members predominantly identify as Black, and all rural BOAA members identify as white and "include military veterans, farmers, and residents of under-resourced communities."

### [Collective for Research Impact and Social Partnerships (CRISP)](https://crisp.wisc.edu/)

Broadly, CRISP focuses on connecting researchers at UW-Madison to external partners. It does not exclusively focus on community engaged research, though there is a branch which does focus on this [topic](https://crisp.wisc.edu/community/).

Within that particular branch, CRISP offers consultations to faculty and staff in L&S at UW-Madison who are interested in incorporating community engagement into their work. This can include, for example, facilitating new community collaborations or writing grant applications.

### [Morgridge Center for Public Service](https://morgridge.wisc.edu/)

The Morgridge Center for Public Service provides a wealth of resources for learning about and funding community engaged partnerships.

Useful contact: Cory Sprinkel, sprinkel\@wisc.edu

#### Engagement

##### [UW South Madison Partnership](https://morgridge.wisc.edu/get-connected-community/uw-south-madison-partnership/)

Physical space designed to facilitate mutually beneficial relationships between community members and university partners. University partners can reserve and use this space to engage community members.

##### [Community-University Mixers](https://morgridge.wisc.edu/events/community-university-mixers/)

Social events designed to give faculty, staff, students and community organizations the opportunity to connect and build relationships.

##### [Community Partnerships & Ourreach (CPO) Staff Network](https://morgridge.wisc.edu/cpo/#upcoming-meetings)

CPO offers resources and meetings for UW-Madison staff members who engage in community-engagement work.

#### Funding

##### [Community University Partnership Awards](https://morgridge.wisc.edu/get-connected-community/community-university-partnership-awards/#apply-for-award)

The Morgridge Center offers several awards for financing the building and/or maintaining of community partnerships. Graduate students, faculty, and staff are all eligible to apply for these awards. Funding amounts are available at \$2,000, \$3,000, and \$5,000.

##### [Community-based Research (CBR) Fund](https://morgridge.wisc.edu/faculty-and-staff-get-connected/community-based-research/#CBRFund)

CBR grants are competitive and designed to support community-based research projects in an amount up to \$7,000. Faculty, staff, and graduate students are eligible to apply. Funding can be used to design and implement a new project, add a CBR component to an existing project, or continue an ongoing CBR project. Proposals must detail how the CBR project will meet community-identified needs.

Funding calls are released in August of each year.

#### Learning

##### [Community-Engaged Scholarship Minor/Graduate Certificate](https://morgridge.wisc.edu/graduate-student-resources/community-engaged-scholarship-minor-graduate-certificate/)

A doctoral minor offered through Civil Society and Community Studies with support from the Morgridge Center consisting of 9-12 credits. It includes mandatory coursework and a capstone project focused on community engagement.

##### [Morgridge Fellows Program](https://morgridge.wisc.edu/faculty-and-staff-get-connected/morgridge-fellows/)

A yearlong learning community designed for UW-Madison faculty, staff, and graduate students interested in furthering their knowledge of community-engaged scholarship. Fellows are expected to attend monthly cohort gatherings, attend small group meetings monthly, participate in two additional events, and explore opportunities to share their work. Each fellow is awarded \$1,500 which can be used for professional or project development.

##### [University-Community Engagement Resource Library](https://canvas.wisc.edu/enroll/GKNCBK)

A Canvas course which includes modules and resources pertaining to community-based research.

### [Community Campus Connectors (C3)](https://communityrelations.wisc.edu/community-campus-connectors)

Aside from the groups listed above, there are a number of units and programs on campus (more than twenty!) who facilitate connections between UW-Madison affiliates and community members.

## Community organizations in Madison

### Substance use/addiction-specific

https://recoverycoalitionofdanecounty.org/

https://www.nova.edu/gsc/index.html

### Identity group-specific

## Terminology

Community advisory board (CAB)

:   definition goes here
