# Graduate Student/Mentor Expectations/Policies


## Lab Communications

Asynchronous communication tools (Slack, email) are distracting, which can prevent deep work.  Constant task switching interferes with complex tasks like writing and coding.  These tools draw our attention and reduce our focus even when we are not checking them, simply by knowing that others may be trying to reach us with them.  These asynchronous communication tools may also be making us miserable.  In the short-term, it is rewarding to respond to a simple request or add a cute emojii for feedback.  However, it is frustrating to try to continuously monitor multiple communication channels through the day, every day.  
However, these tools were developed for a reason.  We do need to communicate regularly because we are pursuing collaborative research aims.  We need a better way to communicate that is efficient but not distracting.  We have a hybrid approach:


### Office hours

We will each hold *office hours* every day from 8:30 - 9:30 am.  Students who have class or practicum conflicts are excused from office hours on those days.  Otherwise, we should all plan to be available to each other during these hours. This way we will each have access to each other every day, though it is not expected that we will actually meet during these office hours every day.  

If you need someone, its a good idea to give them a heads up by indicating that in a slack message earlier that morning or the previous afternoon.  You can initiate communication during office hours either in slack or by phone (or across the desks if you are on campus!).  You might consider a zoom if you need to bring in multiple people in different locations.  

Meetings can be very short (a few minutes) or longer (up to 30 minutes?)  Do not plan to use the full hour as that will prevent others from communicating with this person.   Long meetings, if needed, can be scheduled outside of office hours.

Each of us will also use our office hours each morning to handle asynchronous communications (e.g., email, Slack, Asana messages/tasks).


### Asynchronous or unscheduled communications

We will not remove all asynchronous communications.   They can be efficient for some communication tasks. Urgent needs for communication can also arise unexpectedly.  We need methods for these communications.  They are as follows:

1. **Slack messages**.  Most asynchronous communications will continue to occur in Slack.  Slack messages should be limited to questions or posts that do not require more than one (or two?) responses from one individual.  Examples include:

   * Posts about articles to read, new analysis methods, etc to channels like software-r, read-papers, read-media.  These posts do not require any response but many of us (myself included) find them valuable to read at moments when we are not doing deep work.  
    
   * Questions directed at as single lab member requesting clear information that will not (likely) require follow-up or clarification (i.e., a series of back-and-forth messages over a short period).  We should @ the person within the appropriate channel or DM them.  They will respond the next morning during their office hours.

2. **Task assignments in Asana**.  If we need someone to DO something, don't use Slack.  Asana was designed to track tasks and it does this well.  Assign that person a task directly in Asana.  Set a due date for when you need it (they can adjust this date if necessary to accommodate their own schedule).  Describe the task fully in the description box.  If the task requires discussion, discuss it with them during office hours.  Do NOT engage in a series of back and forth messages in Asana!  Live meetings are appropriate for discussions.  Some messages or update can be posted in Asana.  Expect these messages to be read the next day during the person's office hours.  Use @ to make sure the person sees your message (comment)

3. **Phone calls for urgent communications**.  Urgent communications may be necessary at times.  If you need information from someone immediately, call them.  This will allow us to be available for urgent issues without having to monitor some communication channel.  However, we should very carefully consider how urgent our need is.  We recognize that we are likely disrupting someone else's deep work.   This cost to them should be recognized.   Most issues can wait until the next morning.

4. **Lab notebooks for documentation**.  Slack and Asana were not designed for documentation.  For documentation, we will begin to make heavier use of lab notebooks maintained through Quarto.   There is a strong expectation that we are all contributing to these various documentation efforts.  Its simply too much to be maintained solely by John and Susan.  At this point these notebooks will include:
     * Project manuals - for procedure and materials for a grant funded or other parent project.  These manuals can also include  units on data cleaning, design, hypotheses, etc.  These repos are public and called docs_PROJECTNAME.  We currently have
         * docs_risk
         * docs_risk2
         * docs_face
     * ARC documentation (docs_arc) - A documentation notebook for our lab about general lab issues
     * DWT (dwt) - A web book documenting best practices for data wrangling and visualization using the tidyverse.
    

### Professional Calendaring

We all need to commit to keep our Outlook calendar up to date with all meetings and planned absences during business hours in the work week.  This will allow each of us to view others calendars and use Outlook's scheduler to find times that are available for all of us.  This anticipates that the whole university is pushing to establish Outlook as our "business" calendar.  As adoption increases, this will remove the need for time consuming schedule poll (e.g., whentomeet) for all of us.  I understand that many of you may use other calendars for your personal use.  However, Outlook will be the official work calendar.  If you use other calendaring systems, please make sure that you have shared events in that calendar such that the are viewable (public or private by your choice) in Outlook.   

We may send invites to share Google calendars with you if you are assigned to work on a study with a calendar. These calendars are used to view scheduled sessions for studies. 

## Weekly Lab Meeting

* happen weekly
* everyone is expected to contribute to selecting topics
* everyone is expected to lead some meetings
* post topics and materials by Friday (at the latest) for the next week
* Location TBD.  Outside when possible/pleasant

## Weekly Student/Mentor Meeting


## Research Contributions in the Lab

* Everyone makes contributions to lab projects
* These activities provide:
  * Important training activities
  * Keeps us connected to how the data are collected and cleaned, which is important when we write papers
  * Serves to create data that are used by current and future students (and past students did the same for you!)
* The nature of the contributions often change based on developmental stage and skill set
  * Younger students more often may collect data and/or meet with participants
  * Older students may do more EDA or data management
* Students who are supported as RAs or on university or training fellowship (e.g., Emotion training grant) are expected that to use their hours (up to 20 depending on support) dedicated to a lab project.
* Students who are NRSA supported are expected to work primarily on the aims of that associated grant
* Students who are supporting themselves through teaching will also make contributions but with likely many fewer hours given the demands of their TA
* John will negotiate these assignments each semester as part of discussing your funding


## Mentoring and Study/Paper Collaborations

Ideas under development.   Likely involves more advanced students collaborating as secondary mentors on FYPs.  May also involve first year students collaborating on studies led but more advanced students.

## Authorship expectations
Graduate students will be first authors on their FYP and dissertations in almost all instances.   However, if the student is unable to make progress a published version of their project for an extended period of time and the only way to motivate another student to complete that project is by providing them with first author credit, the authorship order could be changes.  In those instances, the graduate student would still remain a co-author.   Such authorship reordering would only happen following numerous conversations with John about failure to make progress.

Graduate students will be first authors on independent projects that they design with me and lead as part of their larger program of research.  However, as with FYP and dissertations, the authorship order could be changed if progress stalled for an extended period of time.   The bar for re-ordering may be somewhat lower for this type of project than for an FYP/Dissertation.   As with FYP/Dissertation, such re-ordering would only happen following numerous discussions about progress concerns.

Graduate students who work as RA/project coordinator on large (i.e., multi-year) R01s (e.g. NRT1, RISK, DOX) should not assume that they will be the first author of all projects published from that grant except in very exceptional circumstances (e.g., the grant includes a sizable intellectual AND practical contribution from the student).  If the graduate student takes a part of the grant as an FYP/Dissertation, expectations about author follow as described above.  However, there will often be multiple supplemental papers that emerge from an R01 including papers addressing its specific aims and other papers that emerge as the project unfolds.  As these supplemental papers are identified, John will offer them to specific students.  In these instances, John follows these general guiding principles:

*	Is the paper within the student’s current or desired program of research?
* Does the student have the skill set to lead the project (or is this a skill set they want and John can support them developing)?
* Does the student have the time to make reasonable progress on the project?
* Will the project help advance or otherwise support the student’s professional development?
* Has the student make substantial contributions to the lab outside of their own projects (e.g., mentoring; infrastructure development; programming; grant writing)?

John will make these preliminary decisions about first author assignment on supplemental papers transparent (i.e., John will share with grads when such assignments have been established).   This will allow an opportunity for others to negotiate with John if they disagree with the decision.

These first author assignments on supplemental papers is preliminary.  It is not sufficient to simply express interest or otherwise claim a project to guarantee the first author role on these projects.  Authorship order is first established definitively when progress on the project is meaningfully initiated.   Prior to that, the bar to re-offer the project to someone else is relatively low (and likely based on some combination of how much times passes since the project is preliminarily assigned, how motivated John is to get the paper published, and who else is available to take the lead).

Decisions about co-authors and order are negotiated by the first and the senior (John) authors.   These decisions are made on a paper by paper basis after considering many factors (skill set of the first author, professional development goals/needs of other graduate students/staff/undergrads, scope/complexity of the project, etc).  As noted below, the first author will document expectations of contributions from co-authors to allow some accountability as the project progresses.

When projects/papers are first developed, an Asana project will be established for the paper.   The student first author will be responsible for detailing initial expectations about authorship order, contributions, and timeline.  This can be detailed in the studies unit in docs_arc.  This information can be updated if expectations change over time.   Preliminary assignments should be documented here too (by the student).  However, as noted above, preliminary assignments are not finalized until meaningful initiated.

Authorship order changes will not happen without substantial previous discussion.  However, they can happen if expectations about progress are not met.  This is necessary to guarantee that our labs investment of time and resources results in published papers in a timely manner.

We will make every effort to include staff and exceptional undergrads (e.g., Hilldale fellows; Senior theses) as co-authors on papers that they make meaningful contributions.  It is less likely that staff/undergrads will be first author on a project but this can happen in situations where grads are not interested or available to write papers in a timely fashion.

## First Year Student Orientation

The following two documents need to be reviewed and/or completed early in the semester.

-  All first year students should have a “First Year Fall Meeting” with their mentors. The mentor should be filling out the First Year Fall Meeting Form as the conversation progresses (this form must be completed by the mentor; you must be logged into the UW-Google Space).  Basically it’s just a series of checkboxes that you check once you’ve talked about the given topic (e.g., topics related to the FYP, to coursework, to how the lab functions, etc.). 

-  All first year students and their advisors should go over and discuss the (Advisor-Advisee Compact)[http://psych.wisc.edu/wp-content/uploads/2023/09/Advisor-AdviseeCompact_2023.pdf]. This is a pdf and there’s nothing to fill out/submit.  It’s just part of a conversation you should have.  

In addtion, once a Mentoring Committee has been established (i.e., all the faculty members have agreed to serve on the committee and the committee is finalized), the Established Mentoring Committee form should be completed by the student.
