# Lab Resources

## Repositories
A full list of John's GitHub repos can be found [here](https://github.com/jjcurtin?tab=repositories). A few frequently used ones:

* [lab_supoort](https://github.com/jjcurtin/lab_support): Contains R functions, chtc code, and quarto templates written for specific ARC tasks.
* [arc_measures](https://github.com/jjcurtin/arc_measures): Copies of our collected individual difference measures and their scoring code and related reference material. Any questionnaire which is copyrighted will only have our scoring file and a link to the copyright holder, if known.

## Quarto Templates
All of the following templates are quarto files for use in creating lab-related documentation

*  [Simple Quarto Template](https://github.com/jjcurtin/lab_support/blob/main/templates/simple.qmd). This simple template allows you to set margins/font and to switch from HTML to PDF output.


### YAML files

Including these YAML files in a blank .qmd document sets up output for either HTML or PDF, tailored to ARC standards with respect to margins, font, etc.

TBD (CONTENTS NEED TO BE ADDED TO THESE FILES)

*  [HTML YAML](https://github.com/jjcurtin/lab_support/blob/main/templates/yaml_html.qmd)
*  [PD YAML](https://github.com/jjcurtin/lab_support/blob/main/templates/yaml_pdf.qmd)

### Latex Support Files

TBD

*  [includes.tex](https://github.com/jjcurtin/lab_support/blob/main/templates/latex/package_includes.tex) - this file includes frequently used packages and their specifications. (Will expand)
*  [define_headers_arc.tex](https://github.com/jjcurtin/lab_support/blob/main/templates/latex/define_headers_arc.tex) - define H1 - H3 headers per John's specifications
*  [define_headers_apa.tex](https://github.com/jjcurtin/lab_support/blob/main/templates/latex/define_headers_apa.tex) - define H1 - H5 headers per APA specifications
*  [nih_template.tex](https://github.com/jjcurtin/lab_support/blob/main/templates/nih_latex_template.tex) - contains formatting related to NIH grant writing including header and bibliography formatting.


### Manuscripts

#### APA
[.qmd template](https://github.com/jjcurtin/lab_support/blob/main/templates/apa.qmd). This is based on the template at [this repo](https://github.com/wjschne/apaquarto). Our version is currently under development to try and load assets from our lab_support repo rather than installing the extention files locally.

#### CSL files

Below are the YAML code of a couple that we use frequently (linked to the primary CSL repo)

NIH Grant Proposals:  
`csl: https://raw.githubusercontent.com/citation-style-language/styles/master/national-library-of-medicine-grant-proposals.csl`

Elsevier (Vancouver substyle):  
`csl: https://raw.githubusercontent.com/citation-style-language/styles-distribution/f8524f9b9df60e94e98f824f242a1fb27cc9fc59/elsevier-vancouver.csl`

APA 7th Edition:  
`csl: https://raw.githubusercontent.com/citation-style-language/styles/master/apa.csl`

Note: the [apa quarto template](https://github.com/jjcurtin/lab_support/blob/main/templates/apa.qmd) in the `lab_support` repo calls its own version of the apa.csl from within its ex_apa support folder. 

### Grants
TBD

### Other

Letterhead: [.qmd template](https://github.com/jjcurtin/lab_support/blob/main/templates/letterhead.qmd). See Susan or John for assistance in personalizing this for other lab members.

